# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestNewsSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift', '~> 4.4.1'
pod 'Alamofire'
pod 'AlamofireObjectMapper', '~> 5.2'
pod 'SDWebImage'
pod 'Firebase/Auth'  
end
